### ISSUE TITLE
Basic Implementation Decisions

### ISSUE THREAD

**Issue by kiwikern** [dimitrisMaf28/FUcoin#2]
- Should we use the (Akka Framework)[https://github.com/dimitrisMaf28/FUcoin/wiki/Akka-Framework]?
- Should we use Java or Scala?
- Which IDE should we use? IntelliJ, Eclipse,...

**Comment by berkaycura** [comment]
We have decided to use Akka Framework because of the following reasons;
- Scalable real-time transaction processing
- Actor Model
- event-driven, asynchronous -> distributed
- let it crash semantics
- fault tolerance by supervisor hierachies
- messages can be saved -> persistence
- usage:
     library
     sbt (scala dependency manager)
     Typesafe ConductR (dependencies, deployment)
